### ISSUE TITLE
Modern Industrialization

### ISSUE THREAD

**Issue by castilio20** [EnigmaticaModpacks/Enigmatica10#1]
### URL

https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

### Why would you like the mod added?

a good mod that now is on neo and a new aproach for tech (new at least for enigmatica)

**Comment by MommyHeather** [comment]
dammit i should've made a "first" issue

**Comment by MuteTiefling** [comment]
Happy to test it out, at least.

**Comment by MuteTiefling** [comment]
Alright, I'll preface this by saying I'm not against it. However, some things are not entirely clear for me. 

What does this bring to the player? 

In other words, if I look at something like Ars Nouveau, Botania, Create, and other big content mods, you get some nice toys to play with. Spells, transmutations, quarries, equipment, etc. Any time I encounter a newer mod, the first thing I ask myself is "what does this do for me, or what problem is this solving". 

Looking over this mod, I see the following
- Some crazy armor that looks like it'd take the better part of a year to craft. 
- A nice 3x3 drill you can access early on to make early game less of a chore
- A quarry of some sort that looks like it can be pretty nice and absolutely required to obtain materials in the quantities the mod requires
- Storage in the form of Barrels (similar to drawers) and Tanks
- Various power gen options (hard to judge since I can't built them without some kind of guide and Patchouli isn't ported yet)

That seems to be pretty much it. And to be fair, that's largely what any tech mod offers. But here it is all wrapped up in a level of micro crafting that makes automation required and similarly requires massive material inputs. These aren't bad things. But they also need to be considered in the context of other mods in the pack, or likely to be added to the pack. 

Power generation seems like it will be very high, but I assume it will also be very expensive to get to. I doubt anyone will be rushing this mod's nuclear reactor. So while it may blow away anything else, it's self gated.

Storage is likely to be outclassed by something like Sophisticated Storage or AE2. Especially as it appears to lack any form of controller to centrally access barrels.

Other mods add quarries, and while they likely don't generate as much, those mods also aren't using much material either. Meaning this will also outclass any of them, and likely fairly quickly.

This all makes me feel that perhaps there isn't much here beyond the challenge of putting it all together; I can pretty easily go get all this from most any other tech mod for less hassle, after all.

I fear that this would ultimately fall by the wayside in favor of easier methods that are sufficient for the mods they're balanced against. On the other hand, perhaps this would give people some longevity and a long term goal to work towards despite this being a kitchen sink pack. At the worst, it doesn't seem to detract from anything. 

As I said at the start, I'm not against it. But I do need help seeing it through other people's eyes to know what we'd be getting by adding it.

**Comment by NielsPilgaard** [comment]
I'll check it out again once we can read it's manual 😄
