### ISSUE TITLE
EMI showing unavailble items in the Market

### ISSUE THREAD

**Issue by SupaJordy** [EnigmaticaModpacks/Enigmatica10#11]
### Modpack Version

1.2.0

### Describe your issue.

EMI shows that you can get a mushroom in the Market:
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/59a81013-0083-4a96-9c4a-153afc5d4d0c)

But it is not available:
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/410f67b9-42bb-40cd-a69c-994f124ee7ca)

Only these items are currently available in the Market:
![image](https://github.com/EnigmaticaModpacks/Enigmatica10/assets/128645404/30bf4400-6637-4c78-9c07-ad4992951392)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

jordacus

**Comment by MuteTiefling** [comment]
Well that's an odd one :D I'll have a look here, thanks for the report!

**Comment by MuteTiefling** [comment]
Alright... Farming for Blockheads appears to have re-invented the wheel here. 

Recipes for the market now come in 'categories', many of which are disabled by default. They can be enabled/disabled in the config file, which shows/hides them in the Market itself. However, since they're still registered as a recipe, EMI is picking them up. 

Spawn eggs are another default category (disabled). You cannot purchase them because they're disabled, but EMI still tells you you can.

**Comment by MuteTiefling** [comment]
https://github.com/TwelveIterationMods/FarmingForBlockheads/issues/215
