### ISSUE TITLE
Iris Shaders

### ISSUE THREAD

**Issue by purrloftruth** [EnigmaticaModpacks/Enigmatica10#154]
### URL

https://www.curseforge.com/minecraft/mc-mods/irisshaders

### Why would you like the mod added?

Shaders are pretty.
![Screenshot with Complementary Reimagined and Distant Horizons](https://github.com/user-attachments/assets/5e93cc08-6341-46bb-956b-73b1a1121729)

Notes:
* Iris for 1.21.1 is still in beta.
* Iris is not supported by Embeddium. The mainline version of Sodium now has an official NeoForge port (in beta). Like Embeddium, it has inline FRAPI support without adding Indium separately. 
* I've seen a number of other modpacks offer the [Complementary Shaders](https://www.complementary.dev/) with the [Euphoria patches](https://www.curseforge.com/minecraft/mc-mods/euphoria-patches) by default, and if you don't have other preferences these seem like a good default choice.
* The screenshot I took above uses the Complementary Reimagined shaders and also is using Distant Horizons. (I'm not sure how you all would feel about having DH as a mod in the pack by default, so I won't worry about filing a request for that yet)

**Comment by MuteTiefling** [comment]
We generally prefer leaving this up to the player to decide if they want it.

**Comment by NielsPilgaard** [comment]
Those are very valid points 🤔

**Comment by theboo** [comment]
I think the bigger issue might be that we're currently shipping embeddium, and there's currently no possible way to load shaders with embeddium installed in the pack  as the bridge mod Monocle is stuck in license hell trying to support iris(embeddium doesn't work with iris directly, and oculus is dead due to iris existing natively.

So when people ask how to enable shaders in this pack we'll have to tell them to remove embeddium and install sodium/iris... Then they'll have to remove embeddium every time they update the pack, and we're updating fairly frequently

**Comment by NielsPilgaard** [comment]
> I think the bigger issue might be that we're currently shipping embeddium, and there's currently no possible way to load shaders with embeddium installed in the pack as the bridge mod Monocle is stuck in license hell trying to support iris(embeddium doesn't work with iris directly, and oculus is dead due to iris existing natively.
> 
> So when people ask how to enable shaders in this pack we'll have to tell them to remove embeddium and install sodium/iris... Then they'll have to remove embeddium every time they update the pack, and we're updating fairly frequently
> 
> Edit:this sent as soon as I logged on... Idk what happened but most of this is covered by purrloftruth lol

I've been meaning to swap up Embeddium for Sodium anyway, this is a good extra incentive.
