### ISSUE TITLE
ExtendedAE

### ISSUE THREAD

**Issue by blackkiv** [EnigmaticaModpacks/Enigmatica10#62]
### URL

https://www.curseforge.com/minecraft/mc-mods/ex-pattern-provider

### Why would you like the mod added?

This mod improve and helps with ae2 automatization, adding different new blocks. For example: extended pattern provider with 36 slots for patterns, 36 slots interface, infinity cells with cobble/water and etc.

**Comment by StarskyXIII** [comment]
I don't understand why this mod is getting thumbs down.
If you think some items or devices in this mod are too powerful, you can modify the recipes or even disable them.

Besides possibly overpowered devices, this mod also offers some QoL features.

## ME Extended Pattern Access Terminal
> For example, I originally grew oak trees at home and used oak planks as material for my crafting patterns. All the input materials were oak planks. However, today I decided to switch to growing spruce trees and wanted to replace all patterns using oak planks with spruce planks. In the original AE2, there is no quick way to find patterns that use oak planks as input. The ME Extended Pattern Access Terminal, on the other hand, provides a way for players to search for pattern inputs.

![2024-07-31_07 37 32](https://github.com/user-attachments/assets/f66bc0a9-ed0b-41ba-af36-d577c203f748)

## Pattern Viewer
> Add a hotkey to view Pattern

![2024-07-31_07 39 28](https://github.com/user-attachments/assets/200ba6a2-b312-43bf-a7dc-010b0f000f4a)
![2024-07-31_07 39 42](https://github.com/user-attachments/assets/426b57ac-3364-4128-ab8e-2b9a89533bd9)

## More filter types of Storage/Export Buses
> Because why not

![2024-07-31_07 44 42](https://github.com/user-attachments/assets/7a78f247-5630-4006-9e96-5f18c4332f8d)
![2024-07-31_07 44 46](https://github.com/user-attachments/assets/0e72d062-5061-4988-8de3-cd251d4925fc)
![2024-07-31_07 45 08](https://github.com/user-attachments/assets/3680d2ee-f163-4515-adce-87f955384e2e)

## ME Threshold Level Emitter
> It will be helpful for automation

![2024-07-31_07 49 33](https://github.com/user-attachments/assets/e07b0ca3-295a-4774-b7c9-0ceacc110c1d)

## ME Caner
> I know you can use Mekanism's Tank to do something similar, but when there's a device specifically designed for this task, why not?

![2024-07-31_07 53 29](https://github.com/user-attachments/assets/c5caec2a-1b64-41bb-a80e-e3e08e22aa19)
![2024-07-31_07 53 39](https://github.com/user-attachments/assets/6cc658c3-27d8-4667-bf3e-d8584afe72b7)

## Assembler Matrix
> This might be controversial, but as the game progresses and you write more recipes, you'll need to place more and more Pattern Providers and Molecular Assemblers. This can become tedious and monotonous in the endgame. The Assembler Matrix could serve as an interesting endgame multiblock structure.

![2024-07-31_07 57 30](https://github.com/user-attachments/assets/d32a7a1f-19aa-4894-90a3-d07e27f6b702)
![2024-07-31_07 57 36](https://github.com/user-attachments/assets/bd0531e8-3316-48f6-8fe3-efceeaf887a5)

Finally, I just want to express that this mod isn't simply about adding overpowered convenience devices to AE2; it also includes other practical features that might be worth considering. However, whether or not to include it in your modpack is entirely up to you.

**Comment by MuteTiefling** [comment]
The thumbs down is simply because I'm not interested, largely because it seems like a 'X but Bigger' type mod. 

There are already creative solutions to most of what this has to offer. Having to disable most of a mod just for the sake of a couple of features doesn't really sit well with me.

For my part, I'd be much more interested in adding custom recipes to relieve pain points, rather than add a mod and remove more than half of it.

This is why recipes can use tin instead of iron already and powah has the ability to charge crystals. I've been thinking of adding a way to make fluix without the in-world step as well. One exists with MI (which also offers several other QoL recipes out of the box for AE2), but a few more options would be nice.

**Comment by NielsPilgaard** [comment]
I like the Assembler Matrix, I don't like that many of these items remove the need to think creatively to solve problems.

**Comment by DoomSquirter** [comment]
I was going to request this but I see it's already been voted off the island which is sad

There are times when a bigger pattern provider helps a bunch.  

The 4x inscribers are also extremely useful for speeding up things

THE CURE for these things "intelligent options" has a word.

SPAM

Spam more of the normal variants to get the speed or capability you want.  

that is literally the only solution to the above
you make yet another machine and a 9 slot provider to accomodate more patterns

you spam more inscribers till you achieve the desired speed of parts made.

Tbh, I'm not much interested in anything else tho I used a couple other things in another pack but those are the ones I appreciate most.

I will probably be adding the mod manually when the pack updates

**Comment by flece** [comment]
well 745K downloads for AE2 and 326k downloads for ExtendedAE since mid september.  there are a lot of ppl rly want this in there world. i like to also have it in E10 for the "ME Wireless Connector" alone. Remember E10 is not Expert but kitchensink to play with new mods.

so i also will install this manual to the Pack. At least to see for myself if its cluter or big improvement.

BTW: what exactly is the reason for adding AA? iam sure there are already creative solutions to most of what this has to offer ;)

**Comment by NielsPilgaard** [comment]
> BTW: what exactly is the reason for adding AA? iam sure there are already creative solutions to most of what this has to offer ;)

Damn, you caught us there :P

**Comment by MuteTiefling** [comment]
AA also adds its own challenges to meet ^_~

**Comment by flece** [comment]
u know....for me it is ok to add an additional Mod. No matter if it has "Extended" or "Additions" in his name. xD

**Comment by HeatherComputer** [comment]
Yeah add whatever mods you want to your own local installation.

**Comment by flece** [comment]
@NielsPilgaard @MuteTiefling i played around with this mod and would like to see you both checking it out for yourself. Normally i can follow your arguments but not this time. imho it is perfectly balanced, not a single item needs to be removed from pack.

aesthetically perfect fitting the new AE2 look. All items that give you benefit over AE2 come with an fairly huge amount of effort and tradeoff for that.

f.i.: 2 Wireless Connector 32 blocks apart cost you 460 FE/t (276 FE/t if you upgrade with 8x Energy Card)

the only downside i found in E10: the mod adds it own crystal, whats needed for most stuff. and the crystals are not harvested by Amethyst Golem. on the other Hand ... this only makes it harder.

so..this is not like "Extra Cells" that just makes things bigger....it has an different aproach.

to make it clear. i dont want to push my opinion. I just think we miss out on a great addition to pack.
if iam wrong and you have tested it, please take a minute and explain to me what makes it not fitting to pack. many thanks

also: comes with plushies xD
![grafik](https://github.com/user-attachments/assets/ebd5d95c-6a6a-43e1-8d8f-d323ad8c299a)

**Comment by theboo** [comment]
Plushies sold me... Also crystals are a non issue, can easily be made harvestable by the golems of we want... But all I care about now is the plushies

**Comment by HeatherComputer** [comment]
It's the walrus all over again.

**Comment by flece** [comment]
> It's the walrus all over again.

i remember that..it was horrible xD

**Comment by MuteTiefling** [comment]
I did mess around with it a bit when this first came up... But hey, I'll take a poke again. 

> All items that give you benefit over AE2 come with an fairly huge amount of effort and tradeoff for that.

Crafting complexity does not equal effort. That's all going to get automated away with a few recipes. Not that I'm seeing any complexity in the recipes, mind. Components are all pretty standard stuff. The big new resource is just Budding Certus 2.0. 

Where are you seeing Effort and Trade-off?

### Crystal Assembler
Largely used for crafting the new blocks from the mod. Also acts as a faster Inscriber for the purpose of putting together Processors. I think I've covered that portion with custom recipes.

### ME Extended (Pattern Provider | Interface | Drive | Molecular Assembler | IO Port | Export Bus | Import Bus | Did I Miss one? )
This thing but bigger. This isn't a design philosophy that invites players to think about how to approach a solution more effectively. That furnace you're running on a giant pattern provider isn't better than splitting jobs up across multiple furnaces. 

### Ingredient Buffer
Make a subnet. If anything, this is worse than subnets because now you need to route things through other pipes.

### Wireless Connector
Cheap wireless. One singularity to be able to configure them, but otherwise very cheap single block solution to the Quantum Bridge. Sure it's same dim, sure it's short range... but building a Quantum Bridge isn't that big of an ask for wireless. 

### Extended ( Inscriber | Charger )
This thing but 4x
Inscriber and charger recipes have all been given alternatives in the pack already and are either faster, more efficient, or both compared to the default AE2 methods.

### ME Canner
It's a tank. Just put a tank there. Mekanism Tanks will fill buckets incredibly rapidly. 

### Crystal Fixer
We already offer solutions to this through custom recipes with other mods. Though, thanks for the reminder, I need to fix the EMI listing showing this. 

### Circuit Slicer
Already have a few custom recipes to do all these. Can certainly add more if people want alternatives. I was even considering making the PNC processor recipes use blocks instead just to speed them up. Probably will go do that now. 

### ME Void Cell
We have trash cans. 

I don't have the mental energy to go through the rest for a second time right now, but I'm really not seeing anything here that can't be approached already through some mildly creative means. My answer is still the same. I don't see the point of just tossing in 'the same but better'. Could this be neat in an Expert pack? Sure, if we wanted to build recipes around the machines, that could be super fun. It's not a bad mod. It just seems so needless for a normal pack. It'd be like adding Extended Crafting. 

Like I said before, I'm *more than happy* to add recipes to make things different/more efficient/faster through other mods. Things that will get you to go explore those mods and see what they have to offer beyond the custom recipes. I'd much rather people get out of their comfort zone and explore Ars Nouveau to use this funky little golem that makes Certus for me, or get into PNC to improve processor rates, or get into IF to no longer have to in-world fluid, etc... All recipes that exist right now.

**Comment by flece** [comment]
i hear what you are saying but dont understand why it is applied here on this small QoL mod .. but not on AA for instance. for me it boils down to (your) taste. I was thinking the other way around (how does the mod can hurt balance, and need special attention)

i personal found it a a little boring to setup AE2 the same way for the 5. time. at this time i just want autocrafting that work. so really dont mind what mod it provides. This Addon give me back a little fun with something new in that old AE2 and i was assuming that iam not the only one thinking that way,

i respect your opinion(of course!) and your decision(grudgingly)  thank you for the time explaining to me.

**Comment by HeatherComputer** [comment]
> For me it boils down to (your) taste

Making packs based off of pack developer tastes is what gives us unique packs.

**Comment by MuteTiefling** [comment]
In regards to AA, yes it has a lot of overlap. But it's not 'your thing but bigger' overlap. It offers alternatives without stepping on toes. 

And there's some nostalgia there too, I won't lie. It's been years since we could include it and we want to celebrate the fact that it's available again. A lot of love went into bringing it back.

**Comment by DoomSquirter** [comment]
I already said my piece a week ago but I just wanted to throw in one more tidbit

I just threw extended AE onto our E10 server because it wasn't going to be added to the pack proper

My only experience with the mod was in PA2 which is 1.20.1

It seems that between then and now, a massive gating mechanism has been added to the entire mod

None of these things are simply just made with existing parts, etc.

There's an entire new mechanic for a new budding block added by the mod that has no flawless version of it, it seems.  

It also involves quite a few other machines to facilitate turning those outputs into the ingots/casings into more of those machines, etc.

This doesn't move the dial one iota in regards to choosing whether to add the mod to e10.  I'm just throwing it out there that yes, there are some interesting and useful blocks here, but none of them are going to be simple to make

In addition, if e10e ever becomes a thing, there are more things in this mod that could be utilized as gating machines/materials to further that.

So keep that all in mind.
The JEI list of blocks the mod offers
![image](https://github.com/user-attachments/assets/7f0de914-52db-4113-9cfe-509f05592a2a)
also note the plushies.  not sure they were mentioned. :P
