### ISSUE TITLE
Occultism: Dimensional Storage lost all inventory

### ISSUE THREAD

**Issue by Drytchnath** [EnigmaticaModpacks/Enigmatica10#94]
### Modpack Version

1.9

### Describe your issue.

After logging in today it was found that my Dimensional Storage was completely empty.  Last 2 logs provided
[latest.log](https://github.com/user-attachments/files/16717357/latest.log)
[2024-08-21-3.log.gz](https://github.com/user-attachments/files/16717358/2024-08-21-3.log.gz)

### Latest Log

<script src="https://gist.github.com/Drytchnath/cbee5890dcb48aa6202637e7117d45c0.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

Updated Occultism, Modonomicon and Theurgy to latest version to fix issues with pulling items for crafting from EMI in Dimensional Storage

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

tank8912

**Comment by theboo** [comment]
This seems to be the important bit, looks like it happened when trying to save the chunk when you logged out... @klikli-dev might wanna take a look at this... 
https://mclo.gs/rDM40ee#L2388

**Comment by klikli-dev** [comment]
@theboo thank you!
I will add some general code to avoid this type of issue (and only use the one item that cannot be serialized).
In this case the underlying issue was a stable wormhole, and the fact that minecraft is more picky about block entity data now (in the past I could supply just the nbt that I wanted the block entity to take from the item and use that to link it to a target block. Now minecraft always wants a block entity id apparently ... )

**Comment by klikli-dev** [comment]
fixed in release/v1.21.1-1.153.3

**Comment by theboo** [comment]
Awesome, thanks a bunch!
